// <auto-generated />
using System;
using Behoof.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Behoof.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250205015153_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Behoof.Infrastructure.Data.Camera", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Camera");
                });

            modelBuilder.Entity("Behoof.Infrastructure.Data.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImageLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Behoof.Infrastructure.Data.City", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CountryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("City");
                });

            modelBuilder.Entity("Behoof.Infrastructure.Data.Color", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Color");
                });

            modelBuilder.Entity("Behoof.Infrastructure.Data.Country", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("Behoof.Infrastructure.Data.Diagonal", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Diagonal");
                });

            modelBuilder.Entity("Behoof.Infrastructure.Data.Favorite", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("Favorite");
                });

            modelBuilder.Entity("Behoof.Infrastructure.Data.FavoriteItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FavoriteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("FavoriteId");

                    b.HasIndex("ProductId");

                    b.ToTable("FavoriteItem");
                });

            modelBuilder.Entity("Behoof.Infrastructure.Data.HistoryProduct", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("HistoryProduct");
                });

            modelBuilder.Entity("Behoof.Infrastructure.Data.Memory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Memory");
                });

            modelBuilder.Entity("Behoof.Infrastructure.Data.Network", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Network");
                });

            modelBuilder.Entity("Behoof.Infrastructure.Data.Power", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Power");
                });

            modelBuilder.Entity("Behoof.Infrastructure.Data.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("BallAnswer")
                        .HasColumnType("int");

                    b.Property<int?>("BallBatery")
                        .HasColumnType("int");

                    b.Property<int?>("BallCamera")
                        .HasColumnType("int");

                    b.Property<int?>("BallDesign")
                        .HasColumnType("int");

                    b.Property<int?>("BallPortatable")
                        .HasColumnType("int");

                    b.Property<string>("CameraId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ColorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiagonalId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImageLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MaxPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MemoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("MinPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NetworkId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PowerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SystemId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("YearOfRealiseId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ColorId");

                    b.HasIndex("DiagonalId");

                    b.HasIndex("MemoryId");

                    b.HasIndex("NetworkId");

                    b.HasIndex("PowerId");

                    b.HasIndex("SystemId");

                    b.HasIndex("YearOfRealiseId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Behoof.Infrastructure.Data.Supplier", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("Behoof.Infrastructure.Data.SupplierProduct", b =>
                {
                    b.Property<string>("SupplierId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SupplierId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("SupplierProduct");
                });

            modelBuilder.Entity("Behoof.Infrastructure.Data.System", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("System");
                });

            modelBuilder.Entity("Behoof.Infrastructure.Data.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CityId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CountryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavoriteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Passoword")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryId");

                    b.HasIndex("FavoriteId")
                        .IsUnique()
                        .HasFilter("[FavoriteId] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Behoof.Infrastructure.Data.YearOfRealise", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("YearOfRealise");
                });

            modelBuilder.Entity("Behoof.Infrastructure.Data.City", b =>
                {
                    b.HasOne("Behoof.Infrastructure.Data.Country", "Country")
                        .WithMany("City")
                        .HasForeignKey("CountryId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Behoof.Infrastructure.Data.FavoriteItem", b =>
                {
                    b.HasOne("Behoof.Infrastructure.Data.Favorite", null)
                        .WithMany("FavoriteItem")
                        .HasForeignKey("FavoriteId");

                    b.HasOne("Behoof.Infrastructure.Data.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Behoof.Infrastructure.Data.HistoryProduct", b =>
                {
                    b.HasOne("Behoof.Infrastructure.Data.Product", "Product")
                        .WithMany("HistoryProduct")
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Behoof.Infrastructure.Data.Product", b =>
                {
                    b.HasOne("Behoof.Infrastructure.Data.Camera", "Camera")
                        .WithMany("Product")
                        .HasForeignKey("CameraId");

                    b.HasOne("Behoof.Infrastructure.Data.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("Behoof.Infrastructure.Data.Color", "Color")
                        .WithMany("Product")
                        .HasForeignKey("ColorId");

                    b.HasOne("Behoof.Infrastructure.Data.Diagonal", "Diagonal")
                        .WithMany("Product")
                        .HasForeignKey("DiagonalId");

                    b.HasOne("Behoof.Infrastructure.Data.Memory", "Memory")
                        .WithMany("Product")
                        .HasForeignKey("MemoryId");

                    b.HasOne("Behoof.Infrastructure.Data.Network", "Network")
                        .WithMany("Product")
                        .HasForeignKey("NetworkId");

                    b.HasOne("Behoof.Infrastructure.Data.Power", "Power")
                        .WithMany("Product")
                        .HasForeignKey("PowerId");

                    b.HasOne("Behoof.Infrastructure.Data.System", "System")
                        .WithMany("Product")
                        .HasForeignKey("SystemId");

                    b.HasOne("Behoof.Infrastructure.Data.YearOfRealise", "YearOfRealise")
                        .WithMany("Product")
                        .HasForeignKey("YearOfRealiseId");

                    b.Navigation("Camera");

                    b.Navigation("Category");

                    b.Navigation("Color");

                    b.Navigation("Diagonal");

                    b.Navigation("Memory");

                    b.Navigation("Network");

                    b.Navigation("Power");

                    b.Navigation("System");

                    b.Navigation("YearOfRealise");
                });

            modelBuilder.Entity("Behoof.Infrastructure.Data.SupplierProduct", b =>
                {
                    b.HasOne("Behoof.Infrastructure.Data.Product", "Product")
                        .WithMany("SupplierProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Behoof.Infrastructure.Data.Supplier", "Supplier")
                        .WithMany("SupplierProducts")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Behoof.Infrastructure.Data.User", b =>
                {
                    b.HasOne("Behoof.Infrastructure.Data.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId");

                    b.HasOne("Behoof.Infrastructure.Data.Country", "Country")
                        .WithMany("User")
                        .HasForeignKey("CountryId");

                    b.HasOne("Behoof.Infrastructure.Data.Favorite", "Favorite")
                        .WithOne("User")
                        .HasForeignKey("Behoof.Infrastructure.Data.User", "FavoriteId");

                    b.Navigation("City");

                    b.Navigation("Country");

                    b.Navigation("Favorite");
                });

            modelBuilder.Entity("Behoof.Infrastructure.Data.Camera", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("Behoof.Infrastructure.Data.Color", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("Behoof.Infrastructure.Data.Country", b =>
                {
                    b.Navigation("City");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Behoof.Infrastructure.Data.Diagonal", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("Behoof.Infrastructure.Data.Favorite", b =>
                {
                    b.Navigation("FavoriteItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Behoof.Infrastructure.Data.Memory", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("Behoof.Infrastructure.Data.Network", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("Behoof.Infrastructure.Data.Power", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("Behoof.Infrastructure.Data.Product", b =>
                {
                    b.Navigation("HistoryProduct");

                    b.Navigation("SupplierProducts");
                });

            modelBuilder.Entity("Behoof.Infrastructure.Data.Supplier", b =>
                {
                    b.Navigation("SupplierProducts");
                });

            modelBuilder.Entity("Behoof.Infrastructure.Data.System", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("Behoof.Infrastructure.Data.YearOfRealise", b =>
                {
                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
